services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: on-failure
    image: book-store-app
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}
      SPRING_DATASOURCE_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:$DEBUG_PORT"

  frontend:
    depends_on:
      - app
    restart: unless-stopped
    image: book-store-frontend
    build: ./frontend
    ports:
      - $FRONTEND_LOCAL_PORT:80

volumes:
  mysql_data: